// <auto-generated />
namespace EmployeCRUDApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v1_employee_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_employee_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202305261150549_v1_employee_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
