CREATE TABLE COLLEGE(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(20))

CREATE TABLE DEPARTMENT(ID INT PRIMARY KEY,NAME VARCHAR(20),
COLLEGE_ID  INT REFERENCES COLLEGE(ID))


INSERT INTO COLLEGE VALUES('VIVA')
SELECT * FROM COLLEGE

INSERT INTO DEPARTMENT VALUES(10,'CS',1)
SELECT * FROM DEPARTMENT

CREATE TABLE CUSTOMER(CID INT PRIMARY KEY IDENTITY(100,1),
FNAME VARCHAR(10),LASTNAME VARCHAR(10),MOBILE_NO VARCHAR(10))

CREATE TABLE ORDERS(OID INT PRIMARY KEY IDENTITY(10,1),
	ONAME VARCHAR(20),TOTAL_PRICE DOUBLE PRECISION,
	CUSTOMER_ID INT REFERENCES CUSTOMER(CID)
)

CREATE TABLE LINEITEM(ID INT PRIMARY KEY IDENTITY(1,1),
	PNAME VARCHAR(20),QUANTITY INT,
	ORDER_ID INT REFERENCES ORDERS(OID)
)

INSERT INTO CUSTOMER VALUES('Gautam','Pandey','9523527143')
INSERT INTO CUSTOMER VALUES('Sandeep','Pandey','9523556903')
INSERT INTO CUSTOMER VALUES('Raj','Kumar','9523567143')

SELECT * FROM CUSTOMER

INSERT INTO ORDERS VALUES('Gautam Order',10000.56,102)
INSERT INTO ORDERS VALUES('Sandeep Order',12344.67,101)
INSERT INTO ORDERS VALUES('Raj Order',67.89,102)
SELECT * FROM ORDERS

INSERT INTO LINEITEM VALUES('Pen',4,10)
INSERT INTO LINEITEM VALUES('Book',6,13)
INSERT INTO LINEITEM VALUES('Box',7,12)
SELECT * FROM LINEITEM