// <auto-generated />
namespace ContactDALLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v1contact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1contact));
        
        string IMigrationMetadata.Id
        {
            get { return "202305251923411_v1-contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
