CREATE TABLE CUSTOMERS(CID INT PRIMARY KEY,CNAME VARCHAR(20),BALANCE DOUBLE PRECISION)
CREATE TABLE MERCHANT(MID VARCHAR(5) PRIMARY KEY ,NAME VARCHAR(20),BALANCE DOUBLE PRECISION)


INSERT INTO CUSTOMERS VALUES(1,'MANJU',10000)
INSERT INTO CUSTOMERS VALUES(2,'GAUTAM',5000)


INSERT INTO MERCHANT VALUES('M1','RMART',50000)
INSERT INTO MERCHANT VALUES('M2','DMART',60000)

UPDATE CUSTOMERS SET BALANCE =BALANCE+2000 WHERE CID = 1
UPDATE MERCHANT SET BALANCE = BALANCE - 2000 WHERE MID = 'M1'

SELECT * FROM CUSTOMERS
SELECT * FROM MERCHANT