// <auto-generated />
namespace SimpleEFApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v1student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1student));
        
        string IMigrationMetadata.Id
        {
            get { return "202305181117360_v1-student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
