SELECT * FROM EMP
SELECT * FROM DEPT

-- (1). Display All ENAME in Descending
SELECT ENAME FROM EMP ORDER BY ENAME DESC;

-- (2). Display ENAME,SAL,COMM OF EMPLOYEE IN DEPT 10
SELECT ENAME,SAL,COMM 
FROM EMP 
WHERE DEPTNO=10

--ALL EMPLOYEE IN 10 & 20
SELECT ENAME,SAL,COMM 
FROM EMP 
WHERE DEPTNO=10 OR DEPTNO=20

SELECT ENAME,SAL,COMM 
FROM EMP 
WHERE DEPTNO IN(10,20)

-- DISPLAY ALL EMPLOYEES WHO ARE MANAGERS
SELECT * FROM EMP WHERE JOB='MANAGER'

-- EMPLOYEE SAL BETWEEN 2K & 5K
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 5000

-- EMPLOYEE WHOSE COMMISION IS NULL
SELECT * FROM EMP WHERE COMM IS NULL

-- UPDATE NULL COMMISION TO 0
UPDATE EMP SET COMM=0; 
SELECT * FROM EMP

-- CALCULATE CTC OF EACH EMPLOYEE
SELECT ENAME,SAL,COMM,12*(SAL+COMM) AS CTC FROM EMP

-- DISPLAY MIN,MAX,AVG,SUM OF SALARY OF EMPLOYEE
SELECT AVG(SAL) AS 'AVG',MAX(SAL) AS 'MAX',SUM(SAL) AS 'SUM' FROM EMP;

SELECT GETDATE() AS 'TODAY'
PRINT(GETDATE())


SELECT ENAME,HIREDATE,DATEDIFF(YEAR,HIREDATE,GETDATE()) AS 'TENURE' FROM EMP
SELECT * FROM EMP;

-- ALL EMPLOYEE NAME STARTING WITH S
SELECT * FROM EMP WHERE ENAME LIKE 'S%'

-- SELECT UNIQUE DEPTNO FROM EMP TABLE
SELECT DISTINCT DEPTNO FROM EMP

-- SELECT TOP 3 SALARY  EARNING EMPLOYEE
SELECT TOP 3 * FROM EMP ORDER BY SAL DESC

-- DEPEATMENT WISE NO OF EMPLOYEES
SELECT DEPTNO,COUNT(DEPTNO) AS 'NO_OF_EMPLOYEE' 
FROM EMP 
GROUP BY DEPTNO 
ORDER BY COUNT(DEPTNO) DESC;

-- JOBWISE EMPLOYEE COUNT
SELECT JOB,COUNT(JOB) AS 'NO_OF_EMPLOYEE' 
FROM EMP 
GROUP BY JOB 
ORDER BY COUNT(JOB) DESC;

-- DEPTWISE ,JOBWISE EMPLOYEE COUNT
SELECT DEPTNO,JOB,COUNT(*) AS NO_OF_EMPLOYEE 
FROM EMP 
GROUP BY DEPTNO,JOB
ORDER BY COUNT(*) DESC;